# PA4 cpp compiler

.PHONY: all run clean
all: 108501023_PA4.o
		@g++ -std=c++11 108501023_PA4.o -o exe
run:
		@./exe $(input) $(output)
clean:
		@rm *.o
108501023_PA4.o: 108501023_PA4.cpp
		@g++ -std=c++11 -c 108501023_PA4.cpp

		